FROM ubuntu:18.04

RUN apt update && apt install -y \
        software-properties-common && \
    add-apt-repository -y ppa:lramage/sds

RUN apt update && apt install -y \
        automake \
        build-essential \
        curl \
        debhelper \
        devscripts \
        git \
        indent \
        libcurl4-openssl-dev \
        libjansson-dev \
        libjwt-dev \
        libpam0g-dev \
        libsds-dev \
        libssl-dev \
        libtool \
        pkg-config \
        quilt \
        uuid-dev

WORKDIR /usr/src/pam_aad
COPY . /usr/src/pam_aad

RUN tar cvzf ../pam-aad_0.0.1.orig.tar.gz --exclude='.git*' . && \
    debuild -us -uc -i'(.*)' && \
    dpkg -i ../libpam-aad_0.0.1-1_amd64.deb
